### ISSUE TITLE
サーバーフレームワークの選定

### ISSUE THREAD

**Issue by rkun123** [Kyutech-C3/OpenCampus2020#3]
皆さんPythonが使えるようなので、**Pythonでかけるサーバーのフレームワーク**を選定したいと思います。
誰か提案ありませんか？？

**Comment by tokiwameguru** [comment]
Djangoがいいと思います！

**Comment by MasuoK** [comment]
Bottle （pythonほどんど知らない）

**Comment by I-My-Prog** [comment]
フラスコ、ジャンゴ、ジンジャ

**Comment by rkun123** [comment]
Djangoなら強力な[Modelクラス](https://docs.djangoproject.com/ja/3.0/intro/tutorial02/)があってRDB（おそらく今回はPostgreSQL）がとっても使いやすいし、[テンプレート](https://docs.djangoproject.com/ja/3.0/intro/tutorial03/)もentire_designブランチから上がってくるHTMLを加工するだけで行けそうなんですよね。

**Comment by rkun123** [comment]
FlaskやBottleはDBを操作する機能がないので、別途SQLAlchemyあたりを使う必要があるので結構たいへんかなと思ったりしてます。

**Comment by rkun123** [comment]
異論がなければDjangoに決めたいと思うのですがいかがですか？

**Comment by naga-naga** [comment]
異論なしです

**Comment by MasuoK** [comment]
僕も特に異論ないです（というかわかんない）

**Comment by rkun123** [comment]
ではDjangoにしましょう！
