### ISSUE TITLE
embedding_video

### ISSUE THREAD

**Issue by rkun123** [Kyutech-C3/OpenCampus2020#5]
**Describe the solution you'd like**
Unityや3Dモデル以外の展示物の場合，動画で埋め込む場合があると思われます．
そのために，動画埋め込みの手法を考えてほしいです．
私としては，たとえば[Video.js](https://videojs.com/)を使って埋め込むなどの方法が考えられると思われます．

**Describe alternatives you've considered**
ほかには，[Youtubeの埋め込み機能](https://developers.google.com/youtube/iframe_api_reference?hl=ja)を使ってみるというのもいいですね．

**Comment by tokiwameguru** [comment]
おっけー
とりあえずVideo.jsでやってみて無理そうだったらYoutubeに切り替える！

**Comment by tokiwameguru** [comment]
# テスト
Google先生は偉大
[TestVideo.zip](https://github.com/Kyutech-C3/OpenCampus2020/files/4699818/TestVideo.zip)

**Comment by tokiwameguru** [comment]
@tokiwameguru 
ダウンロードしたら映らないじゃないか

**Comment by tokiwameguru** [comment]
@tokiwameguru 
あ、zipファイル解凍してなかった
解凍したら普通に映った

**Comment by rkun123** [comment]
[Video.jsの再生ボタンをセンタリングする方法](https://stackoverflow.com/questions/20051332/videojs-centered-play-button)

**Comment by tokiwameguru** [comment]
## 一応完成版
[VideoSubmit.zip](https://github.com/Kyutech-C3/OpenCampus2020/files/4775571/VideoSubmit.zip)


・最初に表示される再生ボタンのセンタリング済み

・再生、一時停止が切り替わったときに再生ボタン、一時停止ボタンのアニメーションが表示されるようにした

・動画が終わるとリプレイボタンが表示されるようにした


使った画像
![C3play](https://user-images.githubusercontent.com/48623999/84579674-c66a9080-ae0a-11ea-88ee-e4f1d7ac2814.png)
![C3replay](https://user-images.githubusercontent.com/48623999/84579926-18acb100-ae0d-11ea-8943-4602a6e42eda.png)
![C3stop](https://user-images.githubusercontent.com/48623999/84579677-c79bbd80-ae0a-11ea-99c6-709f9bb2ab88.png)
